stages:
  - deploy

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mysql

# Speed up builds
cache:
  key: $CI_BUILD_REF_NAME # changed to $CI_COMMIT_REF_NAME in Gitlab 9.x
  paths:
    - vendor
    - node_modules
    - public
    - .yarn

deploy_production:
  stage: deploy
  script:
    - deploy_laravel chenzifeng yeshm/gongzi gz.y-in.com
  environment:
    name: production
    url: https://gz.y-in.com
  only:
    - master
  tags:
    - yeshmgongzi
